# Prefacio {.unnumbered}

```{r}
source('script/setup.R')
```

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

::: justify
Este informe presenta la metodología y los resultados obtenidos en el marco del proyecto **FONDEF ID21I10297**, en el cual se desarrolló [$SatOri$](https://s4tori.cl){target="blank"}, una aplicación para la optimización del riego en frutales, orientada a mejorar la resiliencia de la agricultura chilena frente al cambio climático. La plataforma modela el potencial hídrico xilemático ($\Psi_s$) con frecuencia diaria y resolución espacial, utilizando datos meteorológicos, imágenes satelitales Sentinel-2 y algoritmos de machine learning. El $\Psi_s$ representa la respuesta hídrica de la planta frente a las condiciones ambientales y de manejo. Además, $SatOri$ estima el umbral mínimo de $\Psi_s$ que pueden alcanzar los árboles antes de comprometer su funcionamiento fisiológico, y a partir de este valor genera recomendaciones sectorizadas de riego, en formato de semáforo, para evitar caídas en la fotosíntesis y pérdidas productivas. El protipo, fue desarrollado para dos huertos de cerezos propiedad de la compañía [Garcés Fruit](https://garcesfruit.com){target="blank"}: campos "La Esperanza" y "Río Claro" (ambos ubicados en la Región O'higgins).

Para incorporar variabilidad en los valores de $\Psi_s$, mejorar la predictibilidad del modelo y evaluar la respuesta fisiológica a distintos niveles de riego, se aplicaron cuatro tratamientos de riego deficitario controlado (RDC) en huertos comerciales de cerezo ubicados en La Esperanza y Río Claro, durante dos temporadas consecutivas (2022–2023 y 2023–2024). Para este fin se midieron tres variables fisiológicas: eficiencia fotosintética ($F_v / F_m$), potencial hídrico xilemático ($\Psi_s$) e índice de área foliar (LAI). Los resultados mostraron diferencias entre tratamientos y entre sitios. En general, los tratamientos RDC permitieron mantener valores estables de ΦP₀ cercanos a 0.8, evitar caídas severas de $\Psi_s$ por debajo del umbral crítico y sostener un LAI adecuado durante el periodo de máximo crecimiento. Además, se estimó el punto de pérdida de turgor (TLP) mediante curvas presión-volumen, con valores más negativos en La Esperanza (-2.54 MPa) que en Río Claro (-2.20 MPa), reflejando una mayor tolerancia al estrés hídrico en el primer sitio.

Finalmente, aunque se evaluó la factibilidad de replicar los enfoques utilizados para el modelado del $\Psi_s$ en la estimación horaria del turgor foliar, no fue posible utilizar los datos obtenidos a partir de sensores YARA-ZIM. La alta sensibilidad de los sensores generó variaciones en la magnitud de los registros tras cada recalibración, y el preprocesamiento necesario para estabilizar las series eliminó diferencias entre sensores, impidiendo un análisis confiable entre tratamientos y temporadas.
:::
