# Introducción {.unnumbered}

```{r}
source('script/setup.R')
```

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

::: justify
El cambio global ha provocado una intensificación de la sequía en distintas áreas del mundo. Entre ellas, Chile Central se caracteriza por presentar un evento de Mega Sequía con pocos análogos en los últimos milenios, registrando desde el 2010 una secuencia ininterrumpida de años con déficits de lluvia promedio de un 20-40% [@garreaud2020]. Este tipo de fenómenos puede llegar a tener importantes impactos en la disponibilidad de agua en cantidad y calidad necesaria para actividades agrícolas, pudiendo repercutir de manera significativa sobre factores sociales y económicos [@garreaud2020; @pena2020]. Ante este escenario, se requieren estrategias de gestión del agua más eficientes que permitan a los productores agrícolas adaptarse a la variabilidad climática [@hulbert2017].

En este contexto, el riego deficitario controlado (RDC) ha sido identificado como una estrategia eficaz para optimizar el uso del agua en cultivos perennes como los frutales, donde las opciones de adaptación son limitadas [@pechan2023]. Esta práctica permite reducir el consumo hídrico sin afectar significativamente la producción ni la calidad de la cosecha, mejorando la eficiencia del recurso disponible [@blanco2019b; @lopez2021]. Entre los frutales de exportación, el cerezo es el segundo producto de mayor valor en la agroindustria chilena, con más de 25.000 hectáreas bajo riego y un mercado aproximado de 1.560 millones de dólares [@cb2020a; @gonzalez2022]. La optimización del riego en este cultivo es fundamental para mejorar la sostenibilidad del sector y mantener su competitividad a nivel internacional. Para ello, el potencial hídrico xilemático del tallo ($\Psi_s$; ~s~ por *steam* o tallo en inglés) —medido a mediodía— se ha establecido como un indicador confiable del estado hídrico de la planta, reflejando tanto las condiciones del suelo como la demanda atmosférica y la respuesta fisiológica del cultivo [@moriana2012; @naor2000]. Su medición tradicional, mediante cámaras de presión [@scholander1964], es laboriosa y poco escalable, lo que ha impulsado el desarrollo de métodos alternativos basados en sensores remotos y modelos predictivos [@jones2004].

El turgor, o presión de turgencia, también es un indicador efectivo del estado hídrico de las plantas. Se define como la presión interna que ejerce el contenido celular contra la pared celular, resultado de la acumulación de agua en la vacuola [@halbritter]. Esta presión es crucial para mantener la rigidez de las células vegetales, lo que lo convierte en un parámetro clave, junto con el potencial hídrico del tallo, para evaluar el estado hídrico de la planta. El turgor puede medirse mediante diversos métodos, siendo los sensores de turgor, como el ZIM, uno de los más empleados debido a su simplicidad y aplicabilidad a prácticamente todas las especies de hojas planas [@bader2014]. A pesar de las limitaciones que presentan en condiciones de campo, su fiabilidad ha sido confirmada en numerosos estudios [@ali2023; @fernandez2014; @lee2012], lo que respalda su uso en la investigación del manejo del agua en cultivos.

Avances recientes en teledetección y aprendizaje automático han permitido estimar indirectamente el $\Psi_s$ mediante el uso de datos espectrales y meteorológicos, ofreciendo una solución escalable para el manejo del riego en tiempo real [@c-b2022; @garofalo2023; @savchik2024]. Satélites como Sentinel-2 (S2), con su alta resolución espacial y frecuencia de revisita, permiten monitorear el estado hídrico de los cultivos a través de índices espectrales y térmicos, que actúan como proxies del estrés hídrico [@addabbo2016; @jamshidi2021; @zhang2017]. Estudios recientes han demostrado la viabilidad de predecir el $\Psi_s$ en cultivos como almendros, olivos y cerezos mediante algoritmos de machine learning, como Random Forest y redes neuronales, alcanzando precisiones variables según las condiciones ambientales y las técnicas empleadas [@savchik2024; @garofalo2023; @c-b2022].

El objetivo principal de esta investigación es optimizar el riego en cerezo, mejorando la eficiencia en el uso del agua mediante un diagnóstico continuo del estrés hídrico de las plantas, a través de la medición del potencial hídrico xilemático del tallo y el turgor de la hoja. Para ello, se plantean los siguientes objetivos específicos: (i) evaluar la respuesta de los cerezos a distintos tratamientos de riego deficitario controlado (RDC) mediante el monitoreo de parámetros fisiológicos ($\Psi_s$, fluorescencia, LAI), variables productivas y calidad de fruta; (ii) evaluar tres algoritmos de machine learning (Random Forest, XGBoost y SVM) para el modelado del $\Psi_s$, integrando datos de Sentinel-2 y datos meteorológicas; (iii) desarrollar un prototipo de servicio web ($SatOri$) que proporcione predicciones de la variación espaciotemporal del $\Psi_s$ y recomendaciones de riego en tiempo real; y (iv) evaluar la factibilidad de replicar los enfoques utilizados para el $\Psi_s$ en la estimación de turgor de manera horaria.
:::
