# Clima

```{r}
source('C:/Hemera/garces/reporte/book/paquetes.R')
```

Las variables climáticas fueron obtenidas de las estaciones meteorológicas de Garces Fruits ubicadas en ambos sitios.

```{r}
data_clima <- read_rds('C:/Hemera/garces/data/data_processed/clima.rds') |>
  mutate(fecha_hora = as.POSIXct(paste0(fecha,' ',hora,':00'), format = "%Y-%m-%d %H:%M"),
         temporada = as.factor(temporada),
         sitio = as.factor(sitio))
  
```

::: panel-tabset
# Temperatura

```{r}
#| fig-width: 13
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_clima |>
  mutate(fecha = ifelse(temporada == '2023-2024',gsub("^2023", "2022", fecha),fecha),
         fecha = ifelse(temporada == '2023-2024',gsub("^2024", "2023", fecha),fecha),
         fecha = as.Date(fecha)) |>
  group_by(temporada,sitio,fecha) |>
  summarise(t_dia = mean(t_media,na.rm=F)) |>
  ggplot(aes(fecha,t_dia,color = sitio)) +
  geom_line() +
  facet_wrap(~temporada, ncol = 1, labeller = as_labeller(names)) +
  labs(x = 'Meses',
       y = 'Temperatura media (°C/dia)',
       color = 'Sitio') +
  scale_color_hue(labels=c('La Esperanza','Rio Claro')) +
  theme_light() +
  theme(text = element_text(size = 18),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```

# Déficit de presión de vapor (VPD)

```{r}
#| fig-width: 13
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_clima |>
  mutate(fecha = ifelse(temporada == '2023-2024',gsub("^2023", "2022", fecha),fecha),
         fecha = ifelse(temporada == '2023-2024',gsub("^2024", "2023", fecha),fecha),
         fecha = as.Date(fecha)) |>
  group_by(temporada,sitio,fecha) |>
  summarise(vpd_dia = mean(vpd_medio,na.rm=F)) |>
  ggplot(aes(fecha,vpd_dia,color = sitio)) +
  geom_line() +
  facet_wrap(~temporada, ncol = 1, labeller = as_labeller(names)) +
  labs(x = 'Meses',
       y = 'VPD medio (mbar/dia)',
       color = 'Sitio') +
  scale_color_hue(labels=c('La Esperanza','Rio Claro')) +
  theme_light() +
  theme(text = element_text(size = 18),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```

# Evapotranspiración de referencia (ET0)

```{r}
#| fig-width: 13
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_clima |>
  mutate(fecha = ifelse(temporada == '2023-2024',gsub("^2023", "2022", fecha),fecha),
         fecha = ifelse(temporada == '2023-2024',gsub("^2024", "2023", fecha),fecha),
         fecha = as.Date(fecha)) |>
  group_by(temporada,sitio,fecha) |>
  summarise(eto_dia = mean(eto,na.rm=F)) |>
  ggplot(aes(fecha,eto_dia,fill = sitio)) +
  geom_bar(stat='identity') +
  facet_wrap(~temporada, ncol = 1, labeller = as_labeller(names)) +
  labs(x = 'Meses',
       y = 'ET0 (mm/dia)',
       fill = 'Sitio') +
  scale_fill_hue(labels=c('La Esperanza','Rio Claro')) +
  theme_light() +
  theme(text = element_text(size = 18),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```

# Precipitación

```{r}
#| fig-width: 13
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_clima |>
  mutate(fecha = ifelse(temporada == '2023-2024',gsub("^2023", "2022", fecha),fecha),
         fecha = ifelse(temporada == '2023-2024',gsub("^2024", "2023", fecha),fecha),
         fecha = as.Date(fecha)) |>
  group_by(temporada,sitio,mes = month(fecha)) |>
  summarise(pp_mes = sum(pp,na.rm=T)) |>
  ungroup() |> 
  mutate(mes = factor(mes,levels = c(8:12,1:5))) |> 
  filter(mes %in% c(8:12,1:5)) |> 
  ggplot(aes(mes,pp_mes,fill = sitio)) +
  geom_bar(stat='identity') +
  facet_wrap(~temporada, ncol = 1, labeller = as_labeller(names)) +
  labs(x = 'Fecha',
       y = 'PP (mm/mes)',
       color = 'Sitio') +
  scale_fill_hue(labels=c('La Esperanza','Rio Claro')) +
  scale_x_discrete(labels = c(8:12,1:5)) +
  theme_light() +
  theme(text = element_text(size = 18),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```
:::
