# Producción

```{r}
source('C:/Hemera/garces/reporte/book/paquetes.R')
```

## Peso total

::: panel-tabset
# Por tratamiento

```{r, results='hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_produccion <- read_rds('C:/Hemera/garces/data/data_processed/cosecha/produccion.rds')

data_cld <- data_produccion |>
  group_by(temporada,sitio) |>
  reframe(cld(peso_total,tratamiento)) |>
  rename(tratamiento = grupo)

add <- diff(range(data_produccion$peso_total))*0.2

data_cld <- data_produccion |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(peso_total)$out) != 0,
                           min(boxplot.stats(peso_total)$out),9999999),
                        boxplot.stats(peso_total)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(peso_total)$out) != 0,
                           max(boxplot.stats(peso_total)$out),-9999999),
                        boxplot.stats(peso_total)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_produccion |>
  ggplot(aes(tratamiento,peso_total,fill = sitio)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(tratamiento, max,label = cld),size=4) +
  facet_grid(sitio~temporada,labeller = as_labeller(names)) +
  labs(y = 'Peso total (kg)',
       x = 'Tratamiento') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))

```

# Por temporada

```{r, results = 'hide'}
#| fig-width: 10
#| fig-height: 5
#| fig-align: center
#| lightbox: true

data_produccion_2 <- data_produccion |>
  filter(sitio == 'la_esperanza') |>
  mutate(temporada = as.factor(ifelse(temporada == '2022-2023',1,2)))

data_cld <- data_produccion_2 |>
  group_by(sitio, tratamiento) |>
  reframe(cld(peso_total,temporada)) |>
  rename(temporada = grupo)

data_cld <- data_produccion_2 |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(peso_total)$out) != 0,
                           min(boxplot.stats(peso_total)$out),9999999),
                        boxplot.stats(peso_total)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(peso_total)$out) != 0,
                           max(boxplot.stats(peso_total)$out),-9999999),
                        boxplot.stats(peso_total)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_produccion_2 |>
  ggplot(aes(temporada,peso_total,fill=tratamiento)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(temporada, max,label = cld),size=4) +
  facet_grid(sitio~tratamiento, scales = 'free_x',labeller = as_labeller(names)) +
  labs(y = 'Peso total (kg)',
       x = 'Temporada') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```
:::

## Rendimiento

::: panel-tabset
# Por tratamiento

```{r, results='hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_cld <- data_produccion |>
  group_by(temporada,sitio) |>
  reframe(cld(rendimiento,tratamiento)) |>
  rename(tratamiento = grupo)

add <- diff(range(data_produccion$rendimiento))*0.2

data_cld <- data_produccion |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(rendimiento)$out) != 0,
                           min(boxplot.stats(rendimiento)$out),9999999),
                        boxplot.stats(rendimiento)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(rendimiento)$out) != 0,
                           max(boxplot.stats(rendimiento)$out),-9999999),
                        boxplot.stats(rendimiento)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_produccion |>
  ggplot(aes(tratamiento,rendimiento,fill = sitio)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(tratamiento, max,label = cld),size=4) +
  facet_grid(sitio~temporada,labeller = as_labeller(names)) +
  labs(y = 'Rendimiento (ton/ha)',
       x = 'Tratamiento') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))

```

# Por temporada

```{r, results = 'hide'}
#| fig-width: 10
#| fig-height: 5
#| fig-align: center
#| lightbox: true

data_produccion_2 <- data_produccion |>
  filter(sitio == 'la_esperanza') |>
  mutate(temporada = as.factor(ifelse(temporada == '2022-2023',1,2)))

data_cld <- data_produccion_2 |>
  group_by(sitio, tratamiento) |>
  reframe(cld(rendimiento,temporada)) |>
  rename(temporada = grupo)

data_cld <- data_produccion_2 |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(rendimiento)$out) != 0,
                           min(boxplot.stats(rendimiento)$out),9999999),
                        boxplot.stats(rendimiento)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(rendimiento)$out) != 0,
                           max(boxplot.stats(rendimiento)$out),-9999999),
                        boxplot.stats(rendimiento)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_produccion_2 |>
  ggplot(aes(temporada,rendimiento,fill=tratamiento)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(temporada, max,label = cld),size=4) +
  facet_grid(sitio~tratamiento, scales = 'free_x',labeller = as_labeller(names)) +
  labs(y = 'Rendimiento (ton/ha)',
       x = 'Temporada') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))

```
:::

## Densidad

::: panel-tabset
# Por tratamiento

```{r, results='hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_cld <- data_produccion |>
  group_by(temporada,sitio) |>
  reframe(cld(densidad,tratamiento)) |>
  rename(tratamiento = grupo)

add <- diff(range(data_produccion$densidad))*0.2

data_cld <- data_produccion |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(densidad)$out) != 0,
                           min(boxplot.stats(densidad)$out),9999999),
                        boxplot.stats(densidad)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(densidad)$out) != 0,
                           max(boxplot.stats(densidad)$out),-9999999),
                        boxplot.stats(densidad)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_produccion |>
  ggplot(aes(tratamiento,densidad,fill = sitio)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(tratamiento, max,label = cld),size=4) +
  facet_grid(sitio~temporada,labeller = as_labeller(names)) +
  labs(y = 'Densidad (frutos/kg)',
       x = 'Tratamiento') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))

```

# Por temporada

```{r, results = 'hide'}
#| fig-width: 10
#| fig-height: 5
#| fig-align: center
#| lightbox: true

data_produccion_2 <- data_produccion |>
  filter(sitio == 'la_esperanza') |>
  mutate(temporada = as.factor(ifelse(temporada == '2022-2023',1,2)))

data_cld <- data_produccion_2 |>
  group_by(sitio, tratamiento) |>
  reframe(cld(densidad,temporada)) |>
  rename(temporada = grupo)

data_cld <- data_produccion_2 |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(densidad)$out) != 0,
                           min(boxplot.stats(densidad)$out),9999999),
                        boxplot.stats(densidad)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(densidad)$out) != 0,
                           max(boxplot.stats(densidad)$out),-9999999),
                        boxplot.stats(densidad)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_produccion_2 |>
  ggplot(aes(temporada,densidad,fill=tratamiento)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(temporada, max,label = cld),size=4) +
  facet_grid(sitio~tratamiento, scales = 'free_x',labeller = as_labeller(names)) +
  labs(y = 'Densidad (frutos/kg)',
       x = 'Temporada') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))

```
:::
