# Calidad

```{r}
source('C:/Hemera/garces/reporte/book/paquetes.R')

data_apariencia <- read_rds('C:/Hemera/garces/data/data_processed/cosecha/apariencia.rds')
```

## Apariencia

### Peso

::: panel-tabset

# Por tratamiento
```{r, results='hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_cld <- data_apariencia |>
  group_by(temporada,sitio) |>
  reframe(cld(peso,tratamiento)) |>
  rename(tratamiento = grupo)

add <- diff(range(data_apariencia$peso))*0.2

data_cld <- data_apariencia |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(peso)$out) != 0,
                           min(boxplot.stats(peso)$out),9999999),
                        boxplot.stats(peso)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(peso)$out) != 0,
                           max(boxplot.stats(peso)$out),-9999999),
                        boxplot.stats(peso)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_apariencia |>
  ggplot(aes(tratamiento,peso,fill = sitio)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(tratamiento, max,label = cld),size=4) +
  facet_grid(sitio~temporada,labeller = as_labeller(names)) +
  labs(y = 'Peso (gr)',
       x = 'Tratamiento') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))

```

# Por temporada
```{r, results = 'hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_apariencia_2 <- data_apariencia |>
  filter(sitio == 'la_esperanza') |>
  mutate(temporada = as.factor(ifelse(temporada == '2022-2023',1,2)))

data_cld <- data_apariencia_2 |>
  group_by(sitio, tratamiento) |>
  reframe(cld(peso,temporada)) |>
  rename(temporada = grupo)

data_cld <- data_apariencia_2 |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(peso)$out) != 0,
                           min(boxplot.stats(peso)$out),9999999),
                        boxplot.stats(peso)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(peso)$out) != 0,
                           max(boxplot.stats(peso)$out),-9999999),
                        boxplot.stats(peso)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_apariencia_2 |>
  ggplot(aes(temporada,peso,fill=tratamiento)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(temporada, max,label = cld),size=4) +
  facet_grid(sitio~tratamiento, scales = 'free_x',labeller = as_labeller(names)) +
  labs(y = 'Peso (gr)',
       x = 'Temporada') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```
:::

### Diametro

::: panel-tabset

# Por tratamiento
```{r, results = 'hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_cld <- data_apariencia |>
  group_by(temporada,sitio) |>
  reframe(cld(diametro,tratamiento)) |>
  rename(tratamiento = grupo)

add <- diff(range(data_apariencia$diametro))*0.2

data_cld <- data_apariencia |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(diametro)$out) != 0,
                           min(boxplot.stats(diametro)$out),9999999),
                        boxplot.stats(diametro)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(diametro)$out) != 0,
                           max(boxplot.stats(diametro)$out),-9999999),
                        boxplot.stats(diametro)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_apariencia |>
  ggplot(aes(tratamiento,diametro,fill = sitio)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(tratamiento, max,label = cld),size=4) +
  facet_grid(sitio~temporada,labeller = as_labeller(names)) +
  labs(y = 'Diametro (mm)',
       x = 'Tratamiento') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```

# Por temporada
```{r, results='hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_apariencia_2 <- data_apariencia |>
  filter(sitio == 'la_esperanza') |>
  mutate(temporada = as.factor(ifelse(temporada == '2022-2023',1,2)))

data_cld <- data_apariencia_2 |>
  group_by(sitio, tratamiento) |>
  reframe(cld(diametro,temporada)) |>
  rename(temporada = grupo)

data_cld <- data_apariencia_2 |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(diametro)$out) != 0,
                           min(boxplot.stats(diametro)$out),9999999),
                        boxplot.stats(diametro)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(diametro)$out) != 0,
                           max(boxplot.stats(diametro)$out),-9999999),
                        boxplot.stats(diametro)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_apariencia_2 |>
  ggplot(aes(temporada,diametro,fill=tratamiento)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(temporada, max,label = cld),size=4) +
  facet_grid(sitio~tratamiento, scales = 'free_x',labeller = as_labeller(names)) +
  labs(y = 'Diametro (mm)',
       x = 'Temporada') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```
:::

# Color

::: panel-tabset

# Por tratamiento
```{r, results = 'hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_cld <- data_apariencia |>
  group_by(temporada,sitio) |>
  reframe(cld(color,tratamiento)) |>
  rename(tratamiento = grupo)

add <- diff(range(data_apariencia$color))*0.2

data_cld <- data_apariencia |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(color)$out) != 0,
                           min(boxplot.stats(color)$out),9999999),
                        boxplot.stats(color)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(color)$out) != 0,
                           max(boxplot.stats(color)$out),-9999999),
                        boxplot.stats(color)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_apariencia |>
  ggplot(aes(tratamiento,color,fill = sitio)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(tratamiento, max,label = cld),size=4) +
  facet_grid(sitio~temporada,labeller = as_labeller(names)) +
  labs(y = 'Grado de color',
       x = 'Tratamiento') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```

# Por temporada
```{r, results='hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_apariencia_2 <- data_apariencia |>
  filter(sitio == 'la_esperanza') |>
  mutate(temporada = as.factor(ifelse(temporada == '2022-2023',1,2)))

data_cld <- data_apariencia_2 |>
  group_by(sitio, tratamiento) |>
  reframe(cld(color,temporada)) |>
  rename(temporada = grupo)

data_cld <- data_apariencia_2 |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(color)$out) != 0,
                           min(boxplot.stats(color)$out),9999999),
                        boxplot.stats(color)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(color)$out) != 0,
                           max(boxplot.stats(color)$out),-9999999),
                        boxplot.stats(color)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_apariencia_2 |>
  ggplot(aes(temporada,color,fill=tratamiento)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(temporada, max,label = cld),size=4) +
  facet_grid(sitio~tratamiento, scales = 'free_x',labeller = as_labeller(names)) +
  labs(y = 'Grado de color',
       x = 'Temporada') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```
:::

## Contenido de azucar

::: panel-tabset

# Por tratamiento
```{r, results='hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_brix <- read_rds('C:/Hemera/garces/data/data_processed/cosecha/brix.rds')

data_cld <- data_brix |>
  group_by(temporada,sitio) |>
  reframe(cld(brix,tratamiento)) |>
  rename(tratamiento = grupo)

add <- diff(range(data_brix$brix))*0.2

data_cld <- data_brix |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(brix)$out) != 0,
                           min(boxplot.stats(brix)$out),9999999),
                        boxplot.stats(brix)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(brix)$out) != 0,
                           max(boxplot.stats(brix)$out),-9999999),
                        boxplot.stats(brix)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_brix |>
  ggplot(aes(tratamiento,brix,fill = sitio)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(tratamiento, max,label = cld),size=4) +
  facet_grid(sitio~temporada,labeller = as_labeller(names)) +
  labs(y = 'Grados brix',
       x = 'Tratamiento') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```

# Por temporada
```{r, results = 'hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_brix_2 <- data_brix |>
  filter(sitio == 'la_esperanza') |>
  mutate(temporada = as.factor(ifelse(temporada == '2022-2023',1,2)))

data_cld <- data_brix_2 |>
  group_by(sitio, tratamiento) |>
  reframe(cld(brix,temporada)) |>
  rename(temporada = grupo)

data_cld <- data_brix_2 |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(brix)$out) != 0,
                           min(boxplot.stats(brix)$out),9999999),
                        boxplot.stats(brix)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(brix)$out) != 0,
                           max(boxplot.stats(brix)$out),-9999999),
                        boxplot.stats(brix)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_brix_2 |>
  ggplot(aes(temporada,brix,fill=tratamiento)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(temporada, max,label = cld),size=4) +
  facet_grid(sitio~tratamiento, scales = 'free_x',labeller = as_labeller(names)) +
  labs(y = 'Grados brix',
       x = 'Temporada') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))

```
:::

## Daño

::: panel-tabset

# Por tratamiento
```{r, results='hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_daño <- read_rds('C:/Hemera/garces/data/data_processed/cosecha/daño.rds') |>
  mutate(daño = 100-(d_nulo/n)*100)

data_cld <- data_daño |>
  group_by(temporada,sitio) |>
  reframe(cld(daño,tratamiento)) |>
  rename(tratamiento = grupo)

add <- diff(range(data_daño$daño))*0.2

data_cld <- data_daño |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(daño)$out) != 0,
                           min(boxplot.stats(daño)$out),9999999),
                        boxplot.stats(daño)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(daño)$out) != 0,
                           max(boxplot.stats(daño)$out),-9999999),
                        boxplot.stats(daño)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_daño |>
  ggplot(aes(tratamiento,daño,fill = sitio)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(tratamiento, max,label = cld),size=4) +
  facet_grid(sitio~temporada,labeller = as_labeller(names)) +
  labs(y = 'Daño (%)',
       x = 'Tratamiento') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```

# Por temporada
```{r, results = 'hide'}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_daño_2 <- data_daño |>
  filter(sitio == 'la_esperanza') |>
  mutate(temporada = as.factor(ifelse(temporada == '2022-2023',1,2)))

data_cld <- data_daño_2 |>
  group_by(sitio, tratamiento) |>
  reframe(cld(daño,temporada)) |>
  rename(temporada = grupo)

data_cld <- data_daño_2 |>
  group_by(temporada,sitio,tratamiento) |>
  reframe(min = min(ifelse(length(boxplot.stats(daño)$out) != 0,
                           min(boxplot.stats(daño)$out),9999999),
                        boxplot.stats(daño)$stats[1])-add,
          max = max(ifelse(length(boxplot.stats(daño)$out) != 0,
                           max(boxplot.stats(daño)$out),-9999999),
                        boxplot.stats(daño)$stats[5])+add) |>
  left_join(data_cld,by=c('temporada','sitio','tratamiento'))

data_daño_2 |>
  ggplot(aes(temporada,daño,fill=tratamiento)) +
  geom_boxplot() +
  geom_text(data = data_cld, aes(temporada, max,label = cld),size=4) +
  facet_grid(sitio~tratamiento, scales = 'free_x',labeller = as_labeller(names)) +
  labs(y = 'Daño (%)',
       x = 'Temporada') +
  theme_light() +
  theme(legend.position = "none",
        text = element_text(size = 14),
        axis.title.y = element_text(margin = margin(r = 17)),
        axis.title.x = element_text(margin = margin(t = 17)))
```
:::