# Preprocesamiento de datos de turgor

```{r}
source('script/setup.R')
```

El preprocesamiento de los datos de turgor consistió en tres etapas principales: filtrado, clustering y modelado. Primero, se eliminaron registros inconsistentes mediante tres criterios: (i) estabilidad en la serie de turgor (diferencias estandarizadas \< 1), (ii) correlaciones esperadas con temperatura y VPD (positiva y negativa, respectivamente) y (iii) una correlación mínima de 0.5 con al menos una de estas variables. Posteriormente, se excluyeron valores fuera del rango temporal relevante.

Luego, se agruparon los datos por sitio, temporada y sensor, calculando estadísticos diarios (mediana, máximo y mínimo) y aplicando clustering con DBSCAN para identificar patrones coherentes. Finalmente, se ajustaron modelos lineales entre turgor y los primeros componentes principales (PC1 y PC2), obteniendo coeficientes de regresión para cada grupo. Con estos parámetros, se generó una serie modelada de turgor a partir de la información PCA y se escaló para comparación.

```{mermaid}
flowchart TD
  A["Datos brutos de turgor (sensor)"] --> B(Clustering)
  B --> C["Datos clusterizados (sensor)"]
  D[Temperatura y VPD] --> E("Limpieza de datos: eliminación de clusters")
  C --> E
  E --> F["Datos clusterizados limpios (sensor)"]
  F --> G(Estandarización de clusters)
  G --> H["Datos preprocesados (sensor)"]
  H --> I["Datos preprocesados (unidad)"]
  H --> J["Datos preprocesados (tratamiento)"]

```
