# Data

## Potencial hídrico xilemático y fluorescencia

::: justify
Posterior a la instalación del sistema de riego diferenciado, se seleccionaron 3 árboles por tratamiento (un total de 15 árboles por campo), teniendo en consideración el efecto de borde, esto con el propósito de monitorear en el tiempo el estatus hídrico de cada planta (3 réplicas por tratamiento). Para ello se emplearon 2 indicadores: (1) Potencial hídrico xilemático al mediodía; cuyas mediciones son consideradas el proxy más preciso del estado hídrico para los cerezos dulces [@blanco2019a; @blanco2019b; @cb2020b; @cb2020a; @houghton2023]. (2) Fluorescencia; el cual constituye un indicador de eficacia de la actividad e integridad de la fotosíntesis y el contenido de la clorofila; lo que permite estudiar mecanismos de respuesta ante condiciones de estrés hídrico [@linke2010; @jimenez2015].

Para medición de los indicadores anteriormente mencionados se realizaron visitas quincenales a cada campo. En lo que respecta a la medición del potencial hídrico xilemático (Ψ~s~), la misma se realizó sobre muestras de hojas colectadas entre 12:00-14:00 h provenientes de cada una de los 15 árboles monitoreados. En cada caso, se seleccionaron hojas maduras y en buen estado, ubicadas en el tercio medio del árbol, con orientación este y cercanas al tronco [@mccutchan2019; @marsal2010; @blanco2019a]. Antes de ser cortadas, cada una de ellas fue envuelta por un período de 30 min en bolsas de papel de aluminio, a modo de lograr bloquear la transpiración y la radiación solar. Posterior a este período, cada hoja fue cortada por el pecíolo y colocada al interior de la cámara Scholander conectada a un cilindro de nitrógeno (Modelo 3000, Soil Moisture Equipment, Santa Barbara, CA, EEUU), donde se aplicó presión negativa hasta observar gotas de agua en el extremo del pecíolo cortado, registrándose la cantidad de megapascales (MPa) necesarios para extraer la primera gota de jugo xilemático.

En lo que respecta a la medición de la fluorescencia, se usó el fluorómetro PAR-FluorPen FP 110/D (PSI, Czech), empleando el método de transitorios de fluorescencia OJIP. Este método permitió obtener diferentes parámetros de rendimiento cuántico de la actividad fotosintética en el PSII y evaluar el potencial impacto del riego deficitario sobre este proceso [@kupper2019]. Para obtener una medida de los parámetros de fluorescencia de la clorofila, el fluorómetro consta de un medidor de luz integrado para lecturas digitales directas de la radiación fotosintéticamente activa en el rango 400 a 700 nm. Para lograr una emisión de fluorescencia roja, es necesario exponer a la luz, hojas que previamente se encontraban adaptadas a la oscuridad [@moreno2008]. Con este fin, el equipo consta de unos dispositivos o "clips" , que se colocan en la hoja previamente y que permiten bloquear todo acceso de luz a una porción de la misma. En nuestro caso, se utilizaron 4 clips por árbol del muestreo, los cuales fueron colocados entre las 11:00-13:00 h, seleccionando hojas que se encontrasen maduras, en buen estado, dentro del tercio medio del árbol y orientadas directamente al sol. Pasado el período de adaptación a la oscuridad (20 minutos), se procedió a hacer las mediciones directas con el fluorómetro, el cual dispone de una memoria interna que permite almacenar los datos de manera secuencial. A efecto de los análisis se utilizaron los siguientes indicadores: Fv/Fm o Φ~P0~ (máxima eficiencia quántica del Fotosistema II), Fo (valor mínimo de fluorescencia) y Fv/Fo (razón entre fluorescencia máxima y mínima)
:::

## Cosecha y evaluación de producción y calidad de la fruta

::: justify
Las cosechas se llevaron a cabo siguiendo el cronograma y la planificación de Garcés Fruit. Las mismas se realizaron el 12/12 del 2022 y 2023 en el campo La Esperanza y el 21/12 del 2022 en el campo Río Claro. En ambos casos, se recolectó la totalidad de los frutos de los 15 árboles que componían el muestreo (3 réplicas por tratamiento). El total de la frutas producidas por cada árbol fueron pesadas en campo mediante el empleo de una balanza digital modelo ACS- 30 LED (peso máximo 30 Kg). Posteriormente, utilizando una balanza electrónica modelo SF-400 (peso máximo 10kg) , se colectó al azar el equivalente de un 1kg de cerezas por cada árbol, los cuales fueron almacenados en envases plásticos y refrigerados en coolers para su posterior traslado al laboratorio. El resto de las muestras de cada árbol fueron examinadas de manera meticulosa en su totalidad, contabilizando aquellas cerezas que presentarán deformaciones y defectos en su forma o superficie, tales como pitting, pudrición, fisuras pronunciadas, sobremaduración, daños en la piel, palidez y frutos dobles. Se guardó registro fotográfico de las cerezas identificadas con daños para su posterior revisión y categorización en el laboratorio. Para esta caracterización se usó como base la guía Australian Cherry Quality Guide (disponible: <https://www.cherrygrowers.org.au>).

Una vez en el laboratorio, las muestras de 1 Kg de cerezas por árbol fueron almacenadas en un refrigerador a 4°C. En un plazo menor de 72 h cada una de ellas fue analizada para evaluar la calidad de fruto, de manera de evitar degradaciones relacionadas con el tiempo de almacenamiento. Para ello, se tomó una submuestra al azar de 20 cerezas por árbol, siguiendo una metodología similar a @blanco2019a , para un total de 60 cerezas por tratamiento. La única condición para que una cereza fuese seleccionada, es que la misma se encuentre en buen estado, esto para disminuir la probabilidad de desviaciones relacionadas con daños experimentados durante el traslado e incurrir en el error de medir cerezas defectuosas.

Para evaluar la calidad de las frutas se consideraron las siguientes variables asociadas a los estándares comerciales: peso por unidad (gr), diámetro (mm) y color. Para medir peso (gr) se utilizó una balanza análica de laboratorio, mientras que para estimar el diámetro se empleó un pie de metro digital (0-150mm). En lo que respecta al color, se siguió la carta de color y la metodología recomendada por el Instituto Nacional de Tecnología Agropecuaria (INTA) (disponible en: <https://inta.gob.ar/documentos/carta-de-color-y-calibre-para-la-cosecha-de-cerezas>). Para ello se empleó una escala numérica del 1-6 , la cual variaba desde un rojo pálido (1) a un caoba oscuro (6). Finalmente, de cada sub-muestra se seleccionaron al azar 5 cerezas adicionales (15 por tratamientos), con las mismas se procedió a medir concentración de sólidos solubles (grados brix) utilizando para ello el refractómetro ATC (Brix 0-32) [@blanco2019a].
:::

## Sentinel 2

::: justify
La misión S2 consta de dos satélites idénticos, S2A y S2B, ambos equipados con un sensor multiespectral que cuenta con 13 bandas espectrales que cubren las regiones visible, infrarrojo cercano e infrarrojo de onda corta, con resoluciones espaciales de 10, 20 y 60 m (ver Tabla S2). En este estudio, utilizamos un total de 106 imágenes S2 (A/B): 54 para la temporada 2022-2023 y 52 para la 2023-2024, capturadas entre octubre y mayo en ambos huertos (cuadrícula T19HCB para La Esperanza y T19HBB para Río Claro). Las imágenes se obtuvieron de la colección corregida atmosféricamente S2 Level-2A de Planetary Computer (Microsoft Open Source et al., 2022), con una frecuencia de 5 días y aproximadamente a las 14:30 hora local (UTC-4). Una máscara fue aplicada basandose en la capa de clasificación de escena (SCL) para los valores correspondientes a “Cloud Shadows,” “Cloud Medium Probability,” y “Cloud High Probability,”.
:::