project:
  type: book
  output-dir: docs

book:
  title: "Informe ID21I10297"
  output-file: "reporte_general"
  author: "M. Abel Herrera y Francisco Zambrano"
  date: today
  page-footer:
    left: |
      Informe de metodologías y resultados proyecto FONDEF ID21I10297.
    right: |
      Este libro fue creado con <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  # site-url: 
  # repo-url: 
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - part: index.qmd
      chapters:
        - summary.qmd
        - intro.qmd
    - part: 'Producción'
      chapters:
        - 001_produccion.qmd
        - 002_calidad.qmd
    - part: 'Variables meteorológicas'
      chapters: 
        - 003_humedad.qmd
        - 004_clima.qmd
    - part: 'Parámetros fisiológicos'
      chapters:
        - 005_parametros.qmd
        - 006_tlp.qmd
    - part: 100_preproceso_turgor.qmd
      chapters: 
        - 101_clustering.qmd
        - 102_limpieza.qmd
        - 103_estandarizacion.qmd
        - 104_preprocesado.qmd
    - part: 'Modelo de potencial y SatOri'
      chapters: 
        - 007_potencial.qmd
        - 008_satori.qmd
    - references.qmd

bibliography: references.bib

filters:
  - lightbox

format:
  html:
    theme: cosmo
    mermaid: 
        theme: neutral
  pdf:
    documentclass: scrreprt

execute:
  echo: false
  warning: false
  message: false

number-depth: 4
lang: es

editor: visual

