project:
  type: book
  output-dir: docs

book:
  title: "Reporte ID23_10297"
  output-file: "reporte_general"
  author: "M. Abel Herrera"
  date: "24/4/2024"
  chapters:
    - part: index.qmd
      chapters:
        - summary.qmd
        - intro.qmd
    - part: 'Producción'
      chapters:
        - 001_produccion.qmd
        - 002_calidad.qmd
    - part: 'Variables meteorológicas'
      chapters: 
        - 003_humedad.qmd
        - 004_clima.qmd
    - part: 'Parámetros fisiológicos'
      chapters:
        - 005_parametros.qmd
        - 006_tlp.qmd
    - part: 100_preproceso_turgor.qmd
      chapters: 
        - 101_clustering.qmd
        - 102_limpieza.qmd
        - 103_estandarizacion.qmd
        - 104_preprocesado.qmd
    - part: 'Capítulo 5: Modelo de potencial'
      chapters: 
        - 0501_potencial.qmd
    - references.qmd

bibliography: references.bib

filters:
  - lightbox

format:
  html:
    theme: cosmo
    mermaid: 
        theme: neutral
  pdf:
    documentclass: scrreprt

execute:
  echo: false
  warning: false
  message: false

number-depth: 4
lang: es

editor: visual

