project:
  type: book
  output-dir: docs
  resources:
    - static/**

book:
  title: "Informe ID21I10297"
  output-file: "reporte_general"
  author: "M. Abel Herrera y Francisco Zambrano"
  date: today
  page-footer:
    left: |
      Informe de metodologías y resultados proyecto FONDEF ID21I10297.
    right: |
      Este libro fue creado con <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  # site-url: 
  # repo-url: 
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - 001_prefacio.qmd
    - 002_intro.qmd
    - part: 'Materiales y método'
      chapters:
        - 101_area_estudio.qmd
        - 102_tratamientos.qmd
        - 103_data.qmd
        - 104_predictores.qmd
        - 105_modelo_potencial.qmd
    - part: 'Producción'
      chapters:
        - 201_produccion.qmd
        - 202_calidad.qmd
    - part: 'Parámetros fisiológicos'
      chapters:
        - 401_parametros.qmd
        - 402_curvas_pv.qmd
        - 403_tlp.qmd
    - part: 500_preproceso_turgor.qmd
      chapters: 
        - 501_clustering.qmd
        - 502_limpieza.qmd
        - 503_estandarizacion.qmd
        - 504_preprocesado.qmd
    - part: 'Modelo de potencial y SatOri'
      chapters: 
        - 601_potencial.qmd
        - 602_satori.qmd
    - references.qmd

bibliography: references.bib

filters:
  - lightbox

format:
  html:
    toc: true
    toc-depth: 4
    toc_expand: false
    theme: cosmo
    mermaid: 
        theme: neutral
  pdf:
    documentclass: scrreprt

engine: knitr

execute:
  echo: false
  warning: false
  message: false

lang: es

editor: visual