# Acerca del Informe {.unnumbered}

```{r}
source('script/setup.R')
```

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

::: justify
Reporte general del proyecto ID21I10297, financiado por la Agencia Nacional de Investigación y Desarrollo (ANID) por medio del proyecto FONDEF IDEA 2021.

Esto proyecto estuvo a cargo del director Dr. Francisco Zambrano Bigiarini de la Universidad Mayor.

Investigadores que participaron el el proyecto:

-   Dr. Francisco Zambrano - Director - Centro Hemera UMayor
-   Dra. Andrea Miyasaka Almeyda - Directora Alterna - Centro CGB UMayor
-   Dr. Felipe de La Hoz - Investigador - Externo
-   Paulina Vidal - Investigadora - Centro Hemera UMayor
-   Idania Briceño - Investigadora - Centro Hemera UMayor

Además, trabajaron como asistentes de investigación los siguientes profesionales:

-   Jesica Garrido - Centro Hemera UMayor
-   Abel Herrera - Centro Hemera UMayor

Para revisar los procedimientos específicos empleados o analizar los resultados del proyecto durante la temporada 2022-2023 de manera independiente, se recomienda acceder al reporte fabricado por Muñoz M. en el siguiente [enlace](https://mherreradiaz.github.io/reporte_general/static/anexos/01_reporte_calidad_produccion.pdf){target="_blank"}.
:::
